---
config:
  layout: elk
---
flowchart LR
    WGSL["WGSL"] --> Naga(["Naga"])
    Naga --> SPIR-V["SPIR-V"]
    SPIR-V --> Driver(["Driver"])
    Driver --> CodeMachine["Code Machine"]
    CodeMachine --> GPU["GPU"]
    GPU@{ shape: trap-t}
    style Naga stroke-width:2px,stroke-dasharray: 2
    style Driver stroke-width:2px,stroke-dasharray: 2
